/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MAIN;

import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Karuro
 */
public class mainframe extends javax.swing.JFrame {

    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
        setLocationRelativeTo(null);
        logsPanel.setVisible(false);
        booklistPanel.setVisible(false);
        booklogPanel.setVisible(false);
        setTitle("CEIT Reading Room Sytem");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ceitlogo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        booklogBTN = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        profileSaveBTN = new javax.swing.JLabel();
        profileUpdateBTN = new javax.swing.JLabel();
        studentnumTF = new javax.swing.JTextField();
        statusTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        genderTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        birthdayTF = new javax.swing.JTextField();
        contactTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        logsBTN = new javax.swing.JLabel();
        booklistBTN = new javax.swing.JLabel();
        booklistPanel = new javax.swing.JPanel();
        booklistSearchTF = new javax.swing.JTextField();
        booklistSearchBTN = new javax.swing.JLabel();
        booklistPrintBTN = new javax.swing.JLabel();
        booklistAddBTN = new javax.swing.JLabel();
        booklistUpdateBTN = new javax.swing.JLabel();
        booklistScrollPane = new javax.swing.JScrollPane();
        booklistTBL = new javax.swing.JTable();
        booklistDeleteBTN = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logsPanel = new javax.swing.JPanel();
        logSearchTF = new javax.swing.JTextField();
        logSearchBTN = new javax.swing.JLabel();
        logPrintBTN = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTBL = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        booklogPanel = new javax.swing.JPanel();
        booklogSearchTF = new javax.swing.JTextField();
        booklogSearchBTN = new javax.swing.JLabel();
        booklogPrintBTN = new javax.swing.JLabel();
        booklogAddBTN = new javax.swing.JLabel();
        booklogUpdateBTN = new javax.swing.JLabel();
        booklogScrollPane = new javax.swing.JScrollPane();
        booklogTBL = new javax.swing.JTable();
        booklogDeleteBTN = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        booklogBTN2 = new javax.swing.JLabel();
        booklogBTN1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booklogBTN.setBackground(new java.awt.Color(102, 102, 102));
        booklogBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklogBTN.setForeground(new java.awt.Color(255, 255, 255));
        booklogBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklogBTN.setText("SIGN-OUT");
        booklogBTN.setOpaque(true);
        booklogBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booklogBTNMouseClicked(evt);
            }
        });
        getContentPane().add(booklogBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 100, 30));

        profilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel5.setText("status");
        profilePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel6.setText("student number");
        profilePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel7.setText("NAME");
        profilePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel8.setText("address");
        profilePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 30));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel9.setText("gender");
        profilePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel10.setText("age");
        profilePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel11.setText("birthday");
        profilePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel12.setText("contact");
        profilePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        profileSaveBTN.setBackground(new java.awt.Color(102, 102, 102));
        profileSaveBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        profileSaveBTN.setForeground(new java.awt.Color(255, 255, 255));
        profileSaveBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileSaveBTN.setText("SAVE");
        profileSaveBTN.setOpaque(true);
        profileSaveBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileSaveBTNMouseClicked(evt);
            }
        });
        profilePanel.add(profileSaveBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 120, 30));
        profileSaveBTN.setVisible(false);

        profileUpdateBTN.setBackground(new java.awt.Color(102, 102, 102));
        profileUpdateBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        profileUpdateBTN.setForeground(new java.awt.Color(255, 255, 255));
        profileUpdateBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileUpdateBTN.setText("UPDATE");
        profileUpdateBTN.setOpaque(true);
        profileUpdateBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileUpdateBTNMouseClicked(evt);
            }
        });
        profilePanel.add(profileUpdateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 120, 30));
        profilePanel.add(studentnumTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 330, -1));
        studentnumTF.setEditable(false);
        profilePanel.add(statusTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 380, -1));
        statusTF.setEditable(false);
        profilePanel.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 380, -1));
        nameTF.setEditable(false);
        profilePanel.add(addressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 380, -1));
        addressTF.setEditable(false);
        profilePanel.add(genderTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 380, -1));
        genderTF.setEditable(false);
        profilePanel.add(ageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 380, -1));
        ageTF.setEditable(false);
        profilePanel.add(birthdayTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 380, -1));
        birthdayTF.setEditable(false);
        profilePanel.add(contactTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 380, -1));
        contactTF.setEditable(false);

        jLabel13.setBackground(new java.awt.Color(204, 51, 0));
        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 51, 0));
        jLabel13.setText("PROFILE");
        profilePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 40));

        getContentPane().add(profilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 540, 600));
        profilePanel.setOpaque(false);

        logsBTN.setBackground(new java.awt.Color(102, 102, 102));
        logsBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        logsBTN.setForeground(new java.awt.Color(255, 255, 255));
        logsBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logsBTN.setText("LOGS");
        logsBTN.setOpaque(true);
        logsBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logsBTNMouseClicked(evt);
            }
        });
        getContentPane().add(logsBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 100, 30));

        booklistBTN.setBackground(new java.awt.Color(102, 102, 102));
        booklistBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklistBTN.setForeground(new java.awt.Color(255, 255, 255));
        booklistBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklistBTN.setText("BOOKLIST");
        booklistBTN.setOpaque(true);
        booklistBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booklistBTNMouseClicked(evt);
            }
        });
        getContentPane().add(booklistBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 100, 30));

        booklistPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        booklistPanel.add(booklistSearchTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 350, 30));

        booklistSearchBTN.setBackground(new java.awt.Color(102, 102, 102));
        booklistSearchBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklistSearchBTN.setForeground(new java.awt.Color(255, 255, 255));
        booklistSearchBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklistSearchBTN.setText("SEARCH");
        booklistSearchBTN.setOpaque(true);
        booklistPanel.add(booklistSearchBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 100, 30));

        booklistPrintBTN.setBackground(new java.awt.Color(102, 102, 102));
        booklistPrintBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklistPrintBTN.setForeground(new java.awt.Color(255, 255, 255));
        booklistPrintBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklistPrintBTN.setText("PRINT");
        booklistPrintBTN.setOpaque(true);
        booklistPanel.add(booklistPrintBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 100, 30));

        booklistAddBTN.setBackground(new java.awt.Color(102, 102, 102));
        booklistAddBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklistAddBTN.setForeground(new java.awt.Color(255, 255, 255));
        booklistAddBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklistAddBTN.setText("ADD");
        booklistAddBTN.setOpaque(true);
        booklistPanel.add(booklistAddBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 30));

        booklistUpdateBTN.setBackground(new java.awt.Color(102, 102, 102));
        booklistUpdateBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklistUpdateBTN.setForeground(new java.awt.Color(255, 255, 255));
        booklistUpdateBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklistUpdateBTN.setText("UPDATE");
        booklistUpdateBTN.setOpaque(true);
        booklistUpdateBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booklistUpdateBTNMouseClicked(evt);
            }
        });
        booklistPanel.add(booklistUpdateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 100, 30));

        booklistTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        booklistScrollPane.setViewportView(booklistTBL);

        booklistPanel.add(booklistScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 490, 400));

        booklistDeleteBTN.setBackground(new java.awt.Color(102, 102, 102));
        booklistDeleteBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklistDeleteBTN.setForeground(new java.awt.Color(255, 255, 255));
        booklistDeleteBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklistDeleteBTN.setText("DELETE");
        booklistDeleteBTN.setOpaque(true);
        booklistPanel.add(booklistDeleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 100, 30));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 51, 0));
        jLabel4.setText("BOOKLIST");
        booklistPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(booklistPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 550, 600));
        booklistPanel.setOpaque(false);

        logsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        logsPanel.add(logSearchTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 350, 30));

        logSearchBTN.setBackground(new java.awt.Color(102, 102, 102));
        logSearchBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        logSearchBTN.setForeground(new java.awt.Color(255, 255, 255));
        logSearchBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logSearchBTN.setText("SEARCH");
        logSearchBTN.setOpaque(true);
        logsPanel.add(logSearchBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 100, 30));

        logPrintBTN.setBackground(new java.awt.Color(102, 102, 102));
        logPrintBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        logPrintBTN.setForeground(new java.awt.Color(255, 255, 255));
        logPrintBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logPrintBTN.setText("PRINT");
        logPrintBTN.setOpaque(true);
        logsPanel.add(logPrintBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 100, 30));

        logTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(logTBL);

        logsPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 490, 400));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setText("LOG");
        logsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        getContentPane().add(logsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 550, 600));
        logsPanel.setOpaque(false);

        booklogPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        booklogPanel.add(booklogSearchTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 350, 30));

        booklogSearchBTN.setBackground(new java.awt.Color(102, 102, 102));
        booklogSearchBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklogSearchBTN.setForeground(new java.awt.Color(255, 255, 255));
        booklogSearchBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklogSearchBTN.setText("SEARCH");
        booklogSearchBTN.setOpaque(true);
        booklogPanel.add(booklogSearchBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 100, 30));

        booklogPrintBTN.setBackground(new java.awt.Color(102, 102, 102));
        booklogPrintBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklogPrintBTN.setForeground(new java.awt.Color(255, 255, 255));
        booklogPrintBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklogPrintBTN.setText("PRINT");
        booklogPrintBTN.setOpaque(true);
        booklogPanel.add(booklogPrintBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 100, 30));

        booklogAddBTN.setBackground(new java.awt.Color(102, 102, 102));
        booklogAddBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklogAddBTN.setForeground(new java.awt.Color(255, 255, 255));
        booklogAddBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklogAddBTN.setText("ADD");
        booklogAddBTN.setOpaque(true);
        booklogPanel.add(booklogAddBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 30));

        booklogUpdateBTN.setBackground(new java.awt.Color(102, 102, 102));
        booklogUpdateBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklogUpdateBTN.setForeground(new java.awt.Color(255, 255, 255));
        booklogUpdateBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklogUpdateBTN.setText("UPDATE");
        booklogUpdateBTN.setOpaque(true);
        booklogUpdateBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booklogUpdateBTNMouseClicked(evt);
            }
        });
        booklogPanel.add(booklogUpdateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 100, 30));

        booklogTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        booklogScrollPane.setViewportView(booklogTBL);

        booklogPanel.add(booklogScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 490, 400));

        booklogDeleteBTN.setBackground(new java.awt.Color(102, 102, 102));
        booklogDeleteBTN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklogDeleteBTN.setForeground(new java.awt.Color(255, 255, 255));
        booklogDeleteBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklogDeleteBTN.setText("DELETE");
        booklogDeleteBTN.setOpaque(true);
        booklogPanel.add(booklogDeleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 100, 30));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("BOOK LOG");
        booklogPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(booklogPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 550, 600));
        booklogPanel.setOpaque(false);

        booklogBTN2.setBackground(new java.awt.Color(102, 102, 102));
        booklogBTN2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklogBTN2.setForeground(new java.awt.Color(255, 255, 255));
        booklogBTN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklogBTN2.setText("PROFILE");
        booklogBTN2.setOpaque(true);
        booklogBTN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booklogBTN2MouseClicked(evt);
            }
        });
        getContentPane().add(booklogBTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, 30));

        booklogBTN1.setBackground(new java.awt.Color(102, 102, 102));
        booklogBTN1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        booklogBTN1.setForeground(new java.awt.Color(255, 255, 255));
        booklogBTN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklogBTN1.setText("BOOK LOG");
        booklogBTN1.setOpaque(true);
        booklogBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booklogBTN1MouseClicked(evt);
            }
        });
        getContentPane().add(booklogBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MAIN/SADUI.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logsBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsBTNMouseClicked
        // TODO add your handling code here:
        logsPanel.setVisible(true);
        profilePanel.setVisible(false);
        booklistPanel.setVisible(false);
        booklogPanel.setVisible(false);
    }//GEN-LAST:event_logsBTNMouseClicked

    private void booklistBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booklistBTNMouseClicked
        booklistPanel.setVisible(true);
        profilePanel.setVisible(false);
        logsPanel.setVisible(false);
        booklogPanel.setVisible(false);
    }//GEN-LAST:event_booklistBTNMouseClicked

    private void booklogBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booklogBTNMouseClicked
        LOGIN lg = new LOGIN();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_booklogBTNMouseClicked

    private void profileUpdateBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileUpdateBTNMouseClicked
        // TODO add your handling code here:
        profileSaveBTN.setVisible(true);
        studentnumTF.setEditable(true);
        nameTF.setEditable(true);
        addressTF.setEditable(true);
        ageTF.setEditable(true); 
        genderTF.setEditable(true);
        birthdayTF.setEditable(true);
        contactTF.setEditable(true);
        statusTF.setEditable(true);
    }//GEN-LAST:event_profileUpdateBTNMouseClicked

    private void profileSaveBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileSaveBTNMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "SUCCESS!");
        profileSaveBTN.setVisible(false);
        studentnumTF.setEditable(false);
        nameTF.setEditable(false);
        addressTF.setEditable(false);
        ageTF.setEditable(false); 
        genderTF.setEditable(false);
        birthdayTF.setEditable(false);
        contactTF.setEditable(false);
        statusTF.setEditable(false);
    }//GEN-LAST:event_profileSaveBTNMouseClicked

    private void booklistUpdateBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booklistUpdateBTNMouseClicked
        // TODO add your handling code here:
        if (booklistUpdateBTN.getText() == "UPDATE"){
            booklistUpdateBTN.setText("SAVE");
        }else {
            booklistUpdateBTN.setText("UPDATE");
        }
    }//GEN-LAST:event_booklistUpdateBTNMouseClicked

    private void booklogUpdateBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booklogUpdateBTNMouseClicked
        if (booklogUpdateBTN.getText() == "UPDATE"){
            booklogUpdateBTN.setText("SAVE");
        }else {
            booklogUpdateBTN.setText("UPDATE");
        }
    }//GEN-LAST:event_booklogUpdateBTNMouseClicked

    private void booklogBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booklogBTN1MouseClicked
        // TODO add your handling code here:
        booklogPanel.setVisible(true);
        profilePanel.setVisible(false);
        booklistPanel.setVisible(false);
        logsPanel.setVisible(false);
    }//GEN-LAST:event_booklogBTN1MouseClicked

    private void booklogBTN2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booklogBTN2MouseClicked
        // TODO add your handling code here:
        booklogPanel.setVisible(false);
        profilePanel.setVisible(true);
        booklistPanel.setVisible(false);
        logsPanel.setVisible(false);
    }//GEN-LAST:event_booklogBTN2MouseClicked
 private void projectIcon(){
     ImageIcon img = new ImageIcon(getClass().getResource("/src/MAIN/ceitlogo.png"));
     setIconImage(img.getImage());
//     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/src/MAIN/ceitlogo.png")));
             
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTF;
    private javax.swing.JTextField ageTF;
    private javax.swing.JTextField birthdayTF;
    private javax.swing.JLabel booklistAddBTN;
    private javax.swing.JLabel booklistBTN;
    private javax.swing.JLabel booklistDeleteBTN;
    private javax.swing.JPanel booklistPanel;
    private javax.swing.JLabel booklistPrintBTN;
    private javax.swing.JScrollPane booklistScrollPane;
    private javax.swing.JLabel booklistSearchBTN;
    private javax.swing.JTextField booklistSearchTF;
    private javax.swing.JTable booklistTBL;
    private javax.swing.JLabel booklistUpdateBTN;
    private javax.swing.JLabel booklogAddBTN;
    private javax.swing.JLabel booklogBTN;
    private javax.swing.JLabel booklogBTN1;
    private javax.swing.JLabel booklogBTN2;
    private javax.swing.JLabel booklogDeleteBTN;
    private javax.swing.JPanel booklogPanel;
    private javax.swing.JLabel booklogPrintBTN;
    private javax.swing.JScrollPane booklogScrollPane;
    private javax.swing.JLabel booklogSearchBTN;
    private javax.swing.JTextField booklogSearchTF;
    private javax.swing.JTable booklogTBL;
    private javax.swing.JLabel booklogUpdateBTN;
    private javax.swing.JTextField contactTF;
    private javax.swing.JTextField genderTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logPrintBTN;
    private javax.swing.JLabel logSearchBTN;
    private javax.swing.JTextField logSearchTF;
    private javax.swing.JTable logTBL;
    private javax.swing.JLabel logsBTN;
    private javax.swing.JPanel logsPanel;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel profileSaveBTN;
    private javax.swing.JLabel profileUpdateBTN;
    private javax.swing.JTextField statusTF;
    private javax.swing.JTextField studentnumTF;
    // End of variables declaration//GEN-END:variables
}
